### PR TITLE
Add geolocation support to find user position and add marker

### PR DESCRIPTION
**Pull request by JoshLew7**
### Summary 
This pull request integrates Geolocation to find the user's position in the world and will allow you to center the map on that location and place a marker there according to the feedback that is pulled from the getCurrentPostion method.

### Screencast
Geolocation Demonstration  (2)

### Test Plan
To test you can just run a local server of the site and an alert will pop up with your current Latitude and Longitude. The map currently has fixed Latitudes and Longitudes because this is where we will be starting our test journey. 

### Notes
This geolocation integration will allow me to turn a latitude /longitude coordinate into an Address with reverse geolocation which will be helpful integration with the directions API.

### CODE REVIEW

**Comment by ptwu** [comment]
Hold on, I thought Geocoding allows for conversion between coords and addresses, not geolocation. Having user position is pretty useful though for things past the MVP.

**Comment by JoshLew7** [comment]
> Hold on, I thought Geocoding allows for conversion between coords and addresses, not geolocation. Having a user position is pretty useful though for things past the MVP.

Yeah I meant to say reverse geocoding to actually find their location but I believe that the Lat/Lng user position stuff is all geolocation. I could be wrong though.

**Comment by JoshLew7** [comment]
> > Hold on, I thought Geocoding allows for conversion between coords and addresses, not geolocation. Having a user position is pretty useful though for things past the MVP.
> 
> Yeah I meant to say reverse geocoding to actually find their location but I believe that the Lat/Lng user position stuff is all geolocation. I could be wrong though.

Scratch that, the navigator.**geolocation**.getCurrentPosition threw me off so I'll refactor for the next  PR.

**Comment by ptwu** [comment]
> > > Hold on, I thought Geocoding allows for conversion between coords and addresses, not geolocation. Having a user position is pretty useful though for things past the MVP.
> 
> > 
> 
> > Yeah I meant to say reverse geocoding to actually find their location but I believe that the Lat/Lng user position stuff is all geolocation. I could be wrong though.
> 
> 
> 
> Scratch that, the navigator.**geolocation**.getCurrentPosition threw me off so I'll refactor for the next  PR. 

ok, thanks for splitting your work into manageable PRs

**Pull request merged**
